
services:
  db:
    image: mariadb:11
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER:     ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    command:
      - uvicorn
      - news_portal.asgi:application
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
