# Generated by Django 5.2.4 on 2025-07-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='approved',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('journalist', 'Journalist'), ('editor', 'Editor')], default='reader', max_length=12),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
