# Generated by Django 5.2.4 on 2025-07-25 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_options_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions_journalists',
            field=models.ManyToManyField(blank=True, help_text='Journalists you follow', related_name='subscriber_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions_publishers',
            field=models.ManyToManyField(blank=True, help_text='Publishers you follow', related_name='subscribers', to='news.publisher'),
        ),
    ]
