# Generated by Django 5.2.4 on 2025-07-25 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_publisher_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter",
            old_name="content",
            new_name="body",
        ),
        migrations.AddField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Approved"), ("D", "Denied")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="author",
            field=models.ForeignKey(
                limit_choices_to={"role": "journalist"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="news.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
